name: Create Kubernetes Cluster using EC2 and Kubeadm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init - Root
        working-directory: ./
        run: terraform init

      - name: Terraform Plan - Root
        working-directory: ./
        run: terraform plan

      - name: Terraform Apply - Root
        if: github.ref == 'refs/heads/main'
        working-directory: ./
        run: terraform apply -auto-approve

      - name: Terraform Init - EC2 Module
        working-directory: ./ec2_instance_module
        run: terraform init

      - name: Terraform Plan - EC2 Module
        working-directory: ./ec2_instance_module
        run: terraform plan

      - name: Terraform Apply - EC2 Module
        if: github.ref == 'refs/heads/main'
        working-directory: ./ec2_instance_module
        run: terraform apply -auto-approve

     # - name: (Optional) Terraform Destroy
     #  if: github.event_name == 'pull_request' && github.event.action == 'closed'
     #   working-directory: ./
     #  run: terraform destroy -auto-approve
        
